use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::error::Error;
use crate::model::Config;

const HEADER: &str = "# Generated by hosttui — do not edit manually\n\n";

pub fn ssh_config_path() -> Result<PathBuf, Error> {
    let home = dirs::home_dir().ok_or(Error::NoConfigDir)?;
    Ok(home.join(".ssh").join("config.hosttui"))
}

pub fn generate(config: &Config) -> String {
    let mut out = String::from(HEADER);

    for group in config.groups() {
        writeln!(out, "# --- {group} ---", group = group.name).unwrap();
        for host in config.hosts_in_group(&group.name) {
            write_host(&mut out, host);
        }
    }

    let ungrouped = config.ungrouped_hosts();
    if !ungrouped.is_empty() {
        writeln!(out, "# --- ungrouped ---").unwrap();
        for host in ungrouped {
            write_host(&mut out, host);
        }
    }

    out
}

fn write_host(out: &mut String, host: &crate::model::Host) {
    writeln!(out, "Host {}", host.alias).unwrap();
    writeln!(out, "    HostName {}", host.hostname).unwrap();
    writeln!(out, "    User {}", host.user).unwrap();

    if host.port != 22 {
        writeln!(out, "    Port {}", host.port).unwrap();
    }

    if let Some(ref id) = host.identity_file {
        writeln!(out, "    IdentityFile {id}").unwrap();
    }

    for (key, val) in &host.extra {
        writeln!(out, "    {key} {val}").unwrap();
    }

    writeln!(out).unwrap();
}

pub fn export(path: &Path, config: &Config) -> Result<(), Error> {
    let contents = generate(config);

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::WriteConfig {
            path: parent.to_path_buf(),
            source: e,
        })?;
    }

    let tmp = path.with_extension("hosttui.tmp");

    fs::write(&tmp, &contents).map_err(|e| Error::WriteConfig {
        path: tmp.clone(),
        source: e,
    })?;

    fs::rename(&tmp, path).map_err(|e| Error::WriteConfig {
        path: path.to_path_buf(),
        source: e,
    })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Host};
    use tempfile::TempDir;

    fn host(alias: &str, hostname: &str, user: &str, port: u16, group: Option<&str>) -> Host {
        Host {
            alias: alias.into(),
            hostname: hostname.into(),
            user: user.into(),
            port,
            identity_file: None,
            group: group.map(Into::into),
            extra: vec![],
            details: "".into(),
        }
    }

    #[test]
    fn generate_basic() {
        let config = Config::new(
            vec![
                host("web1", "10.0.0.1", "deploy", 22, Some("prod")),
                host("db", "10.0.0.2", "admin", 5432, Some("prod")),
                host("local", "127.0.0.1", "me", 22, None),
            ],
            vec![Group {
                name: "prod".into(),
            }],
        );

        let output = generate(&config);

        assert!(output.contains("Host web1\n"));
        assert!(output.contains("    HostName 10.0.0.1\n"));
        assert!(output.contains("    User deploy\n"));
        assert!(
            !output.contains("    Port 22"),
            "default port should be omitted"
        );
        assert!(output.contains("    Port 5432\n"));
        assert!(output.contains("# --- prod ---"));
        assert!(output.contains("# --- ungrouped ---"));
        assert!(output.contains("Host local\n"));
    }

    #[test]
    fn generate_with_identity_and_extras() {
        let config = Config::new(
            vec![Host {
                alias: "box".into(),
                hostname: "example.com".into(),
                user: "root".into(),
                port: 22,
                identity_file: Some("~/.ssh/mykey".into()),
                group: None,
                extra: vec![("ForwardAgent".into(), "yes".into())],
                details: "".into(),
            }],
            vec![],
        );

        let output = generate(&config);
        assert!(output.contains("    IdentityFile ~/.ssh/mykey\n"));
        assert!(output.contains("    ForwardAgent yes\n"));
    }

    #[test]
    fn export_round_trip() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.hosttui");

        let config = Config::new(vec![host("srv", "10.0.0.1", "admin", 22, None)], vec![]);

        export(&path, &config).unwrap();

        let contents = fs::read_to_string(&path).unwrap();
        assert!(contents.contains("Host srv\n"));
        assert!(contents.starts_with("# Generated by hosttui"));
    }

    #[test]
    fn generate_empty_config() {
        let config = Config::new(vec![], vec![]);
        let output = generate(&config);
        assert_eq!(output, HEADER);
    }
}
